### ISSUE TITLE
Java 18 Error - unable to decode keystore

### ISSUE THREAD

**Issue by pivotal-david-osullivan** [paketo-buildpacks/libjvm#158]
## What happened?

Running a build with Java 18 (`BP_JVM_VERSION`=18) fails with an error:

```
  BellSoft Liberica JRE 18.0.0: Contributing to layer
    Downloading from https://github.com/bell-sw/Liberica/releases/download/18+37/bellsoft-jre18+37-linux-amd64.tar.gz
    Verifying checksum
    Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
unable to invoke layer creator
unable to load certificates
unable to read keystore
unable to decode keystore
 got invalid magic
```

This seems to be an issue with the change to the `cacerts` file format in Java 18 and the library libjvm uses to read and load from the keystore file.

We will investigate further and work on a resolution, in the meantime, Java versions 8-17 should be used.

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
An update:

In Java 18, the [JVM no longer uses JKS keystores](https://bugs.openjdk.java.net/browse/JDK-8275252). This has broken the certificate importer.

Short term, we'll be disabling the certificate importer. You will not be able to use ca-certificates buildpack in conjunction with Java 18, but it'll allow applications to applications to build.

Long term, we're evaluating Go libraries we can use to build the keystore in the way that Java 18 expects it. There are some challenges though as the current library targets JKS and the popular Go library for PKCS12 does not support the password-less/MAC-less keystores that the JVM wants.

**Comment by pivotal-david-osullivan** [comment]
The following buildpacks have just been released with the ca-certificate helper disabled for Java 18:

- Bellsoft Liberica v9.3.1 
- Paketo Java Buildpack v6.16.1
- Paketo Java Native Image Buildpack v7.15.1

Other JVM provider buildpack releases will follow later this week.

As mentioned in the short term solution above, this workaround should allow builds with Java 18 to succeed but without the ca-certificates buildpack functionality.

**Comment by mecseid** [comment]
Hello @dmikusa and @pivotal-david-osullivan!
Is there any update about this issue?
As I understand, the currently used library only targets JKS, and you didn't find any usable Go library that supports PKCS12 without a password/MAC.

This feature would be nice to work again because Java provided keystore contains much less CA than OpenSSL.

**Comment by dmikusa** [comment]
@mecseid we are kind of at the mercy of the project maintainer. There is a proposed PR that resolves the issue, but it hasn't been merged yet. The issue is here https://github.com/SSLMate/go-pkcs12/issues/32 the PR is here https://github.com/SSLMate/go-pkcs12/pull/39

**Comment by mecseid** [comment]
I hope the maintainer will have some time for that project because it looks like to me it's been abandoned since September.
Wouldn't it be a good solution to fork the project and merge the necessary changes?

**Comment by dmikusa** [comment]
I'd thought about it. I can't speak for others on the Paketo team, but I do not have the cryptographic knowledge to maintain that package, so I'm not really comfortable doing that. I'm sure I could merge this particular PR, but what then? It would just become our fork not being maintained.

If this project isn't maintained and we can't get this PR merged, we'll have to look for a different golang project that is maintained or a different way to manage the certs that is maintainable. I don't like it, but maybe shell out to `keytool` or something else.

**Comment by mecseid** [comment]
Yes, I completely understand the situation, it is a very difficult decision as to what the next right step would be.
As I see it, the fork wouldn't make anything worse, because the main package hasn't been maintained for almost a year, so the buildpack just wins with it while the team can find a better library for the same purpose.

**Comment by modulo11** [comment]
I think this issue will become serious once the next LTS of Java is shipped around September 2023. I did some analysis and took a look at some of the options we have.

## Current State

Using [keystore-go](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4), calling these functions:

- [`SetTrustedCertificateEntry`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L87C43-L89), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#KeyStore.SetTrustedCertificateEntry)
- [`Load`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L189-L191), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#KeyStore.Load)
- [`Store`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L208-L210), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#KeyStore.Store)

and using these types:

- [`TrustedCertificateEntry`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L79C22-L85), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#KeyStore)
- [`Certificate`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L81-L84), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#Certificate)
- [`KeyStore`](https://github.com/paketo-buildpacks/libjvm/blob/26e7f5f6c781206bf4eb5efbcaeb068592ec8d02/certificate_loader.go#L181-L213), [docs](https://pkg.go.dev/github.com/pavlo-v-chernykh/keystore-go/v4#KeyStore)

## Options/Ideas

Switch from [keystore-go](https://github.com/pavlo-v-chernykh/keystore-go) to upstream [go-pkcs12](https://github.com/SSLMate/go-pkcs12) after [PR#39](https://github.com/SSLMate/go-pkcs12/pull/39) was merged. This would be my go-to solution if the project would be properly maintained.

Fork go-pkcs12 and maintain the library. This is very costly and at least I have no prior experience in writing crypto code.

Copy the relevant parts (and only maintain them) of go-pkcs12 into an `internal` package and use that directly. This could be worth a spike and if the maintainer returns to the upstream project, it can be removes again. However, this approach comes with the some of the same issues as the former one.

Add a temporary password to the keystore (e.g. using `keytool`), use go-pkcs12 or [x/crypto/pkcs12](https://pkg.go.dev/golang.org/x/crypto/pkcs12) to manipulate it and remove the password later. I haven't tried that yet, but might also be a potential spike.

Stick to `JKS` format internally and invoke `keytool -importkeystore ...` to import the certificates into `PKCS12`. If all JVMs ship such a store, there could just be two implementations similarly to the debugging options. I guess it would be a relatively small change necessary to support this in libjvm.

Directly operate on the keystore using `keytool -importcert -trustcacerts`. This should also be rather straight-forward and easy to implement. The current architecture of `keystore-go` split into reading, manipulating the object in memory and writing it back to disk. For a large number of added ca-certs, this looks like the the superior approach. I don't expect this to be an issue with a reasonable amount of ca-certs.

## Suggested Actions

- Extract interface for keystore handling (we can do this now and later swap the implementation)
  - This might be just the current method, i.e. `Load(path string, password string) error`
- Discuss different ideas

**Comment by dmikusa** [comment]
> Directly operate on the keystore using keytool -importcert -trustcacerts. This should also be rather straight-forward and easy to implement. The current architecture of keystore-go split into reading, manipulating the object in memory and writing it back to disk. For a large number of added ca-certs, this looks like the the superior approach. I don't expect this to be an issue with a reasonable amount of ca-certs.

I believe that this approach was tried previously, albeit a long time ago, and the performance of `keytool` was not good (multiple seconds). I think the problem was having to run `keytool` once per cert to trust, and there's around 130 certs in a typical environment. This added up to seconds of time, whereas the go solution can do it in a fraction of a second.

It wouldn't hurt to re-test, but IMHO `keytool` is not exactly a speedy tool so I doubt it would be better unless you can get it to process and import the entire bundle of certs with one command. Then perhaps it would be faster.

We could use a different tool, like `openssl`. It can import into a pkcs12 bundle. I'm just not sure if that's a good idea as it ties us to the stack and I'm not sure I like doing that. We might be able to get a statically built binary and have the buildpack install that, but that is more overhead and work. Probably not worth it.

> Add a temporary password to the keystore (e.g. using keytool), use go-pkcs12 or [x/crypto/pkcs12](https://pkg.go.dev/golang.org/x/crypto/pkcs12) to manipulate it and remove the password later. I haven't tried that yet, but might also be a potential spike.

I'd be OK with this. I'd suggest a slight modification though. Run `keytool` and add a random password. We should then be able to use the go libraries to build up the truststore, then instead of taking the password off which would require running `keytool` again, just set the command line flag to tell the JVM the default truststore password. This would allow you to only run `keytool` once to add the password and get the speed of import with the Go library. Unless running `keytool` the second time does not add a perceptible difference in time (I suspect it will though).

>Stick to JKS format internally and invoke keytool -importkeystore ... to import the certificates into PKCS12. If all JVMs ship such a store, there could just be two implementations similarly to the debugging options. I guess it would be a relatively small change necessary to support this in libjvm.

I think this is my preference. I see it as slightly better than the previous solution as you only run `keytool` once and you wouldn't need to set a password on the default truststore. That said, keytool is doing more work so I'd want to test and see how quickly it can import everything into a PKCS12 file from a JKS file.

> Extract interface for keystore handling (we can do this now and later swap the implementation)

100% 👍

**Comment by dmikusa** [comment]
@modulo11 Hi, I just wanted to check if you are planning to support a PR for this issue. It's totally OK if you are not. I was planning to work on this and just wanted to make sure before I start so we're not both working on the same thing. Thanks!

**Comment by modulo11** [comment]
We plan to, but I do not have any clue when we will start working on it. Just add a comment here once you start and I make sure we do as well if we start.

**Comment by modulo11** [comment]
I started working on this today.

**Comment by dmikusa** [comment]
As luck would have it, I started working on that last night. Not a ton of work, mostly just getting an older branch that @pivotal-david-osullivan had started up to date. I've pushed it up to https://github.com/paketo-buildpacks/libjvm/tree/keystore-fix. I'll back off for now. Feel free to take code from that or ignore it completely :)

**Comment by modulo11** [comment]
I first focused on the performance implications of calling `keytool` once to import certificates from another keystore:

| Certificates                     | Time    |
| -------------------------------- | ------- |
| 137 (default SapMachine ca-certificates) | 375ms   |
| 138                              | 370ms   |
| 147                              | 381ms   |
| 237                              | 400ms   |
| 1137                             | 573ms   |
| 10137                            | 1552ms  |

This shows the added startup time to an application which I think is reasonable. There are two potential issues I faced during my testing:

- This [regex](https://github.com/paketo-buildpacks/libjvm/blob/39d42aa892292dd8a196981f1fdc00f81c4b346b/certificate_loader.go#L113) allows only exactly 10 certificates to be loaded. I guess that's a bug and it should rather be `^[[:xdigit:]]{8}\.[\d]+$`, allowing also files like `/layers/paketo-buildpacks_ca-certificates/ca-certificates/ca-certificates/cbf06781.42`
- I wasn't able to get custom certificates into the keystore during launch-time. The order in which helpers are executed seems to be always: 1st `openssl-certificate-loader`, 2nd `ca-certificates-helper`. This looks like the behavior defined in the [spec](https://github.com/buildpacks/spec/blob/platform/v0.11/platform.md#execution), executing `Paketo Buildpack for SapMachine` 1st and `Paketo Buildpack for CA Certificates` 2nd. It only works if certificates are embedded during build-time using `BP_EMBED_CERTS`

**Comment by dmikusa** [comment]
Out of curiosity did you time imports using the current go library? I wonder how things compare 🤔  I think that would really put things into perspective.

**Comment by modulo11** [comment]
Sure, it's way slower. Adding a temporary password to the keystore should be way faster and only add constant amount of time.

# Performance

## Launch Java 17

| Certificates                     | Time  |
| -------------------------------- | ----- |
| 137 (default SapMachine ca-cert) | -     |
| 138                              | 7ms   |
| 147                              | 8ms   |
| 237                              | 12ms  |
| 1137                             | 51ms  |
| 10137                            | 373ms |

## Launch Java 20

| Certificates                     | Time   |
| -------------------------------- | ------ |
| 137 (default SapMachine ca-cert) | -      |
| 138                              | 376ms  |
| 147                              | 387ms  |
| 237                              | 417ms  |
| 1137                             | 618ms  |
| 10137                            | 1942ms |

Meanwhile, I've uploaded the code of my POC https://github.com/paketo-buildpacks/libjvm/tree/pkcs12-cert-loader.

**Comment by modulo11** [comment]
Removing the password from an existing keystore seems to be tricky. We did not manage to do that using `keytool` only. 

However, we looked at the code in [go-pkcs12](https://github.com/SSLMate/go-pkcs12) (which seems really unmaintained) and the necessary parts we would need for writing back a password-less keystore. We ended up with around 200 (copied) lines of code. This could also be a way to go. WDYT?

**Comment by dmikusa** [comment]
I really don't want to pull the code into libjvm. I think that couples the code with libjvm too much. I'm not saying I want to but I'd rather we have a fork of the go-pkcs12 library and pull the code into libjvm. I also think that would make it easier to keep tabs on what happens upstream if anything.

----------

I wonder if we might be able to get away with another variation on this option:

> Add a temporary password to the keystore (e.g. using keytool), use go-pkcs12 or [x/crypto/pkcs12](https://pkg.go.dev/golang.org/x/crypto/pkcs12) to manipulate it and remove the password later. I haven't tried that yet, but might also be a potential spike.

So the purpose of adding the temporary password is so that go-pkcs12 can load certs from that file. I'm not 100% sure we need to do that though. The buildpack presently loads the keystore, then imports all of the openssl certs into the keystore, and this results in a huge amount of duplication because the default Java keystore has basically the same set of certs that we get from the stack images.

I wonder if we could just have go-pkcs12 read all of the openssl/system certs into a new keystore with a password and then have the buildpack set `javax.net.ssl.trustStorePassword` to the password we use, probably `changeit` for historical reasons.

I think this variation would allow us to use the existing library and not need to run keytool at all, or am I overlooking something? Besides the fact that this could result in a discrepancy if the JVM truststore shipped with a CA cert that was not included in the stack images (although one could just add it with the ca-certs buildpack). Thoughts?

--------

For what it's worth, I also did a spike to investigate loading the certificates into a keystore using Java & compiling that to a native-image binary. It was better, around 175ms for 137 certs, but still not close to the go library. That would also require us to bundle a 12M binary into the image, which is probably a deal breaker.

**Comment by modulo11** [comment]
> I wonder if we could just have go-pkcs12 read all of the openssl/system certs into a new keystore with a password and then have the buildpack set `javax.net.ssl.trustStorePassword` to the password we use, probably `changeit` for historical reasons.
> I think this variation would allow us to use the existing library and not need to run keytool at all, or am I overlooking something? Besides the fact that this could result in a discrepancy if the JVM truststore shipped with a CA cert that was not included in the stack images (although one could just add it with the ca-certs buildpack). Thoughts?

I quickly compared the certificates shipped with the `ca-certificates` package from Ubuntu and the `cacert` shipped with SapMachine 20:

- 137 certificates in `ca-certificates` package
- 91 certificates included in SapMachine key store
- 66 certificates found in both
- 25 additional certificates in SapMachine key store which are not part of `ca-certificates` package

Other JVMs would be similar I guess. I would not feel comfortable to only make the ca-certs usable for apps. Could lead to hard to debug issues if apps behave differently (related to certificates) when running locally (using the JVM cacers) and when build with buildpacks.

One risk I see when using go-pkcs12 is that it's unmaintained and critical dependency (gladly there's only one) bumps are missing.

> UPDATE: Hmm, maybe we could also have the buildpack at build time after installing the JVM, rewrite the default truststore so that it has a password. It could use keytool to import all the certs from the old keystore into a new one with a password. It's not great that it would add 370ms of time to the build, but that's only going to happen once per JVM install cause of caching and it's not a huge deal since builds usually take multiple seconds anyway. Then at runtime, we'd basically do what we are doing now.

If we opt in for go-pkcs12 we could do the first part (during build) using the library as is. I did not understand the second part. How could we reuse the current JKS coding?

**Comment by dmikusa** [comment]
> Other JVMs would be similar I guess. I would not feel comfortable to only make the ca-certs usable for apps. Could lead to hard to debug issues if apps behave differently (related to certificates) when running locally (using the JVM cacers) and when build with buildpacks.

I thought that the overlap was higher with Bellsoft, like almost all of them overlap, but I didn't go back and double-check.

I agree with your point though, especially that this could vary from one JVM vendor to another and that it would make things less predictable.

> One risk I see when using go-pkcs12 is that it's unmaintained and critical dependency (gladly there's only one) bumps are missing.

Yes, I agree with this as well. I will say that this particular library probably doesn't need a lot of maintenance though, the format really isn't changing. Given the performance implications of the other options, and that it delays the start-up of applications (not just build), I'd say it's worth the risk. If there is a vulnerability, then we'll need to address that when/if it happens.

> If we opt in for go-pkcs12 we could do the first part (during build) using the library as is. I did not understand the second part. How could we reuse the current JKS coding?

Sorry, I misspoke. You're right, presently it's just using JKS. I was getting confused because @pivotal-david-osullivan had coded some of this up before. He has an implementation [here](https://github.com/paketo-buildpacks/libjvm/compare/main...keystore-fix#diff-ded8b0a49a2218188a4ad8acb0f94d7aa4f4a9fdf38363f9b72d418c5c2c01e0R1) where it can load both. Basically, we can use that and add the bit to rewrite with a password at build time. I think we can go this route and have both, all the JVM ca certs and all the systems certs.

**Comment by modulo11** [comment]
To summarize, we'd collect all certificates (ubuntu ca-certificates + JVM keystore), write that to a new key store (using go-pkcs12) with some password (probably `changeit`) and configure the new location plus the password using Java properties. The initial PR should contain the latest version of `golang.org/x/crypto` to close the known vulnerabilities.

As you and @pivotal-david-osullivan already have the implementation at hand, I'd suggest that you provide the PR. WDYT?

**Comment by dmikusa** [comment]
> To summarize, we'd collect all certificates (ubuntu ca-certificates + JVM keystore), write that to a new key store (using go-pkcs12) with some password (probably changeit) and configure the new location plus the password using Java properties. The initial PR should contain the latest version of golang.org/x/crypto to close the known vulnerabilities.

Yes, but expanding a bit. We still need to run the SSL loader at runtime as well. We can do that with go-pkcs12 though, since we'll set a password on the keystore file at build time.

> As you and @pivotal-david-osullivan already have the implementation at hand, I'd suggest that you provide the PR. WDYT?

I'm fine with that. I can try to get the branch updated with this logic here soon.

**Comment by modulo11** [comment]
Oh, that's interesting. I hope there are no PKCS12 keystores using the standard JKS password instead. I'll run a quick check on the available Java buildpacks to see.
JKS should be easily detectable by reading the magic number. Maybe some if-not-jks-then-pkcs12 is already sufficient?

**Comment by modulo11** [comment]
Looks like it's a Azul thing:

| Vendor           | Version | Keystore | Password |
| ---------------- | ------- | -------- | -------- |
| Amazon Corretto  | 20      | PKCS12   | no       |
| Bellsoft         | 20      | PKCS12   | no       |
| Oracle           | 20      | PKCS12   | no       |
| Eclipse Adoptium | 20      | PKCS12   | no       |
| SapMachine       | 20      | PKCS12   | no       |
| Azul             | 20      | JKS      | yes      |

**Comment by dmikusa** [comment]
> JKS should be easily detectable by reading the magic number.

Do you have a link to something that explains this more? I was just trying to read, then failing if it can't read, but this sounds more accurate/efficient.

**Comment by modulo11** [comment]
Looks like support for password-less keystores in go-pkcs12 is coming with https://github.com/SSLMate/go-pkcs12/pull/48.

If the first 4 bytes of a file are [`FEEDFEED`](https://github.com/openjdk/jdk/blob/7539cc092d0a6b5604351d19e555101fcff75f58/src/java.base/share/classes/sun/security/provider/JavaKeyStore.java#L97) it's considered a JKS keystore. I found this [library](https://github.com/h2non/filetype) for experiments/inspiration.

**Comment by anthonydahanne** [comment]
and... https://github.com/SSLMate/go-pkcs12/pull/48 is merged 🎉

**Comment by modulo11** [comment]
I put together a [branch](https://github.com/paketo-buildpacks/libjvm/compare/pkcs12-cert-loader) extracting a `Keystore` interface with implementations for JKS and PKCS12:

```go
type Keystore interface {
	Add(name string, block *pem.Block) error
	Write() error
}
```

The concrete keystore is detected (`DetectKeystore(path string)`) by magic number (PKCS12) or defaulted to JKS. Any thoughts?

**Comment by dmikusa** [comment]
👍 I think it looks good. That's exactly what I was hoping for in terms of being able to auto-detect off the file type. That way we can avoid the version table of who's using what with which version of Java.

The only thing that jumped out, and it's minor, I don't think we can remove `IsBeforeJava18`. It's a public method, so technically that's a breaking change. Other things could be using it. It seems harmless to me to leave in there, but if you want you could mark it deprecated, and that would allow us to remove it in v2 of libjvm.

Also, speaking of v2, we'll definitely need to port this one to libjvm v2.

**Comment by pax95** [comment]
Hi
Any eta on when this i going to be released ?

**Comment by pax95** [comment]
Thanks @dmikusa for the quick and helpfull fix.
Looking forward to the release.

**Comment by dmikusa** [comment]
Apologies, it should have gone out last week, but it looks like we didn't publish a release last week. I'll check into it and it should go out tomorrow. We almost always cut releases on Friday.

**Comment by dmikusa** [comment]
Again apologies @pax95. I just cut Java 10.4.0. This has the fixes included. You can `pack build --buildpack paketo-buildpacks/java ...` if you want to use it right away. The builders should catch up shortly and include that version, you can always run `pack builder inspect <builder>` to check if it's been updated to include that version. 

Let me know if you're still seeing issues. Thanks

**Comment by honsdomi** [comment]
Hi, is there any change that has to be done to make this work for Java 21? I can see in the logs, that the certificates are loaded fine but it fails in runtime with "unable to find valid certification path to requested target" error. It worked previously with java.version 17. 

```
BellSoft Liberica JRE 21.0.1: Contributing to layer
    Downloading from https://github.com/bell-sw/Liberica/releases/download/21.0.1+12/bellsoft-jre21.0.1+12-linux-amd64.tar.gz
    Verifying checksum
    Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
    Adding 180 container CA certificates to JVM truststore
    Writing env.launch/BPI_APPLICATION_PATH.default
```

**Comment by dmikusa** [comment]
No, it looks to be working cause you see it's adding certificates from the container to the JVM.

> Adding 180 container CA certificates to JVM truststore

There is an edge case that was missed, see https://github.com/paketo-buildpacks/libjvm/pull/344, where it does not load default JVM CA certs. It just loads from the system store in the container and overwrites the JVM keystore. Thus, if the CA cert you need is not in the container's system store, but happens to be in the JVM's default store, then it would come up missing.

The log snippet above is also from build time. You should see a similar message that is logged at runtime, before your app starts. If you're seeing the error at runtime, then you'd want to make sure that happens when your app starts, otherwise, that could be a cause of missing CA certs too.

**Comment by phlppnhllngr** [comment]
I am facing the same issue as @honsdomi on Java 21.
At build time, 139 certificates seem to be added:
```
[INFO]     [creator]     Paketo Buildpack for CA Certificates 3.6.7
[INFO]     [creator]       https://github.com/paketo-buildpacks/ca-certificates
[INFO]     [creator]       Launch Helper: Contributing to layer
[INFO]     [creator]         Creating /layers/paketo-buildpacks_ca-certificates/helper/exec.d/ca-certificates-helper
[INFO]     [creator]       CA Certificates: Contributing to layer
[INFO]     [creator]         Added 2 additional CA certificate(s) to system truststore
[INFO]     [creator]         Writing env.build/SSL_CERT_DIR.append
[INFO]     [creator]         Writing env.build/SSL_CERT_DIR.delim
[INFO]     [creator]         Writing env.build/SSL_CERT_FILE.default
(...)
[INFO]     [creator]         Expanding to /layers/paketo-buildpacks_bellsoft-liberica/jre
[INFO]     [creator]         Adding 139 container CA certificates to JVM truststore
[INFO]     [creator]         Writing env.launch/BPI_APPLICATION_PATH.default
[INFO]     [creator]         Writing env.launch/BPI_JVM_CACERTS.default
```

Then at runtime, the 2 additional ones are missing:
```
Adding 137 container CA certificates to JVM truststore
Spring Cloud Bindings Enabled
```

This was working with Java 17. Any tips?

**Comment by dmikusa** [comment]
The issue mentioned previously has been fixed, so if you're still seeing issues make sure that you are including the certificates at runtime as well as at build time, or use the feature in ca-certificates buildpack to embed the certificates into the build image. https://github.com/paketo-buildpacks/ca-certificates/?tab=readme-ov-file#configuration

If that doesn't help, please start a new thread on the [Discussion Forum](https://github.com/orgs/paketo-buildpacks/discussions).

**Comment by dmikusa** [comment]
The original issue has been patched and released, so I'm closing out this issue. If you come across this thread and are still seeing issues that seem related, please start a new [Discussion Forum thread](https://github.com/orgs/paketo-buildpacks/discussions) and provide details about your specific situation.
