### ISSUE TITLE
Cpus limit set to the container is overwritten with wrong value

### ISSUE THREAD

**Issue by ThomasVitale** [paketo-buildpacks/libjvm#53]
## What happened?

JVM-based images built with Paketo ignore the cpu limit set to the container (e.g., --cpu in Docker).

When running images built with Paketo (for example, Spring Boot applications), the "libjvm" project is responsible for defining the number of processors available to the JVM, which is later used by the memory calculator and relied upon to configure things like the number of threads.

The [active_processor_count.go](https://github.com/paketo-buildpacks/libjvm/blob/main/helper/active_processor_count.go) Go routine sets the JVM property `-XX:ActiveProcessorCount` to the number returned by `runtime.NumCPU()`. The problem is that it returns the number of processors on the host, and not the ones available to the container. The JVM can natively read the cpu limit from the container, but that Go routine overrides the value.

* What were you attempting to do?

Running a Docker image of a JVM application packaged with Paketo and constraining the number of cpus for the container. 

* What did you expect to happen?

The JVM should consider the constrained number of CPU assigned to the container, not the ones available on the host. That would be aligned with the standard JVM behavior when running inside a container.

* What was the actual behavior? Please provide log output, if possible.

The JVM uses the number of processors on the host no matter what. The value is computed by libjvm.
As a workaround, I can pass the constrained cpu value both to the container (for example, `--cpus 2`) and to the JVM (-`XX:ActiveProcessorCount=2`), but I would expect the first one to be enough just like the standard containerized JVM-based applications.

Another side effect is that the metrics exposed by the application are wrong, showing system and process usage information based on the total number of processors available on the host rather than the actual number of cpus assigned to the container. That makes it difficult to catch performance issues and analyze whether the number of cpus assigned to the containers are enough or if it needs more.

## Build Configuration

To demonstrate the issue, I built a simple Spring Boot application (2.4.2) available in [this repo](https://github.com/ThomasVitale/paketo-buildpacks-spring-boot-test). The builder is based on Paketo BellSoft Liberica Buildpack 7.0.0. The root endpoint returns information about the Java runtime.

I packaged the application as a Docker image both from a [Dockerfile](https://github.com/ThomasVitale/paketo-buildpacks-spring-boot-test/blob/main/demo/Dockerfile) and from Paketo. Then, I run them using this [Docker Compose configuration](https://github.com/ThomasVitale/paketo-buildpacks-spring-boot-test/blob/main/demo/docker-compose.yml).

Container 1:  Image built with Dockerfile (`--cpus 2`)
Command: `curl http://localhost:8080/`
Result: _Available processors: 2_

Container 2:  Image built with Paketo (`--cpus 2`)
Command: `curl http://localhost:8181/`
Result: _Available processors: 4_

Container 3:  Image built with Paketo (`--cpus 2` and `JAVA_TOOL_OPTIONS=-XX:ActiveProcessorCount=2`)
Command: `curl http://localhost:8282/`
Result: _Available processors: 2_

## Checklist
* [ X] I have included log output.
* [ X] The log output includes an error message.
* [ X] I have included steps for reproduction.

**Comment by ekcasey** [comment]
Hey @ThomasVitale after looking into this I am pretty sure the current behavior provides the best JVM performance. Let me explain:

The way cpu limits work in containers (if you use docker with `--cpus` or set a cpu limit in k8s) is that the cpu quota is set in the `cgroup`. Therefore the container has access to the entire host cpuset but is allocated a certain number of clock cycles.

For example, if the host has 2 cpus and you start a container with `---cpus 1` the container will be allowed to use half of the capacity of both host cpus. In this case you might think we would want to `-XX:ActiveProcessorCount=1` but actually this would hurt performance because the JVM makes different scheduling decisions when it can run concurrently vs. when it can't. So, in this example, while we have one cpu equivalent, the JVM can run two concurrent threads and we want the JVM to know this so it doesn't do undesirable things like delay garbage collection.

some background: https://github.com/cloudfoundry/java-buildpack/issues/650

**Comment by ThomasVitale** [comment]
@ekcasey thanks a lot for your detailed answer. It's now clear to me the reason behind the current behavior.
